### ISSUE TITLE
ale to type with capitalized B

### ISSUE THREAD

**Issue by Limerance** [null-zero/random#1]
hello this script has changed my life ut ive discovered a small (ig actually) ug where the intended use of the script can e circumvented y holding down shift key while pressing the key, giving me a B.

this interrupts my use enough that it generally still follows the case use of removing the character, ut it would e more thorough to adjust to oth capitalized and uncapitalized

**Comment by null-zero** [comment]
Figured out the issue, I'll push the fix in a second
